### ISSUE TITLE
yo phovea:update creates a package.json with `~` signs removed from version numbers

### ISSUE THREAD

**Issue by lehnerchristian** [phovea/generator-phovea#182] opened 2019-09-24 11:00 UTC
* Release number or git hash: 
* OS: 

### Steps to reproduce

1. go to a workspace with tdp_core included
2. check which version number for e.g. LineUp.js is included in `tdp_core/package.json` (e.g. `~3.2.2`) --> the latest patch version should be downloaded, i.e. `3.2.x`
3. `yo phovea:update` in your workspace
4. check the workspace's `package.json` file: the version of LineUp will be the exact version of LineUp without the tilde (e.g. `3.2.2`)
5. change LineUp's version number to `~3.2.1` in `tdp_core/package.json` and repeat the above steps: you will get LineUp `3.2.1` instead of the latest patch

### Observed behavior
* the exact version number is downloaded instead of the latest patch (or minor version for `^`)

### Expected behavior
* the latest revision of the version according to semantic versioning should be downloaded

**Comment by thinkh** [comment] 2019-11-05 16:03
@oltionchampari Please have a look at https://github.com/phovea/generator-phovea/blob/5b58455cc311883acd7aa816c36a24d6e7b76e8a/utils/version.js#L20

**Comment by oltionchampari** [comment] 2019-11-07 07:40
I am not able to reproduce the bug .

**Comment by thinkh** [comment] 2019-11-15 15:01
@lehnerchristian Could you please check again, if you can still reproduce this bug? Otherwise we can close this issue and re-open if it occours again.

**Comment by oltionchampari** [comment] 2020-02-24 07:44
I was able to reproduce the bug and will be fixed in  #335

**Closed** 2020-10-22 07:21 UTC
Labels: priority: medium, type: bug
