### ISSUE TITLE
Change Webpack.config: JSON.stringify of buildId

### ISSUE THREAD

**Issue by anita-steiner** [phovea/generator-phovea#264] opened 2019-12-04 10:44 UTC

**Comment by thinkh** [comment] 2019-12-20 15:03
I would argue that the current implementation in the webpack.config.js and build.js is correct, because the `const buildId` is already a string. Using another JSON.stringify would assign `"20191220-122223"` (with quotes) to the version variable.

https://github.com/phovea/generator-phovea/blob/82c46aa0e84e08c7cd1ca0dfb6e32f5e4b6a57d2/generators/_init-web/templates/plain/webpack.config.js#L18-L19

https://github.com/phovea/generator-phovea/blob/3a25093aec527c9edb5a89472cbb09f84dfc3408/generators/init-product/templates/plain/build.js#L17-L18

@anita-steiner Do you agree? If yes, please close the issue, as it is correct in the current implementation.

**Comment by thinkh** [comment] 2020-04-14 09:13
Duplicate of #345

**Closed** 2020-04-14 09:14 UTC
Labels: status: duplicate, type: bug
